config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails do
    resources :doses, only: [:new, :create]
  end
  resources :doses, only: [:index, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, presence: true
  validates :name, :uniqueness => true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, :cocktail, :ingredient, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, presence: true
  validates :name, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to cocktail_path(@cocktail), notice: 'Cocktail was successfully created.'
    else
      render :new
  end
end

private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(doses_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail), notice: 'Dose was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktails_path(@dose.cocktail_id)
  end

private

  def doses_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<div class="home-banner">
  <h1>The Cocktail Shop</h1>
  <h2 style="color: #f1e0d0; margin-top: 20px;">Shake a cocktail or <%= link_to 'Add a new mix', new_cocktail_path, class: "index-btn" %></h2>
</div>
<div class="middle-body">
  <div class="container">
    <div class="cards-grid">
      <% @cocktails.each do |cocktail| %>
        <%= link_to cocktail_path(cocktail) do %>
          <div class="card">
            <% if cocktail.photo.attached? %>
              <%= cl_image_tag cocktail.photo.key, class: "img" %>
            <% else %>
              <img class="img" src= "https://images.unsplash.com/photo-1610218587984-c3ed94c74743?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80" alt="cocktail">
            <% end %>
            <p><%= cocktail.name %></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container" style="background-color: #fdce92; width: 900px; height: 100vh; padding: 30px">
  <h1 style="text-align: center;">Add your Cocktail</h1>
  <div class="second-container" style="padding-top: 30px;">
    <img src="https://images.unsplash.com/photo-1610218588440-8e666863342f?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=668&q=80", alt="cocktail image" style="height: 450px; width: 400px; object-fit: cover; margin-left: 20px;">
    <div class="rightside">
      <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name %>
      <%= f.input :photo, as: :file %>
      </br>
      <div>
        <%= f.button :submit, class: "btn" %>
      <% end %>
    </br>
      <%= link_to 'Homepage', cocktails_path, class: "btn-small" %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container" style="width: 900px; height: 100vh; background-color: #fdce92; padding: 30px">
  <h1 style="text-align: center;"><%= @cocktail.name %></h1>
    <div class="second-container"; style="padding-top: 30px";>
      <div style="width: 400px; height: 450px">
        <% if @cocktail.photo.attached?%>
          <%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>
        <% end %>
      </div>
      <div class="rightside">
        <h2>Ingredients</h2>
        <% @cocktail.doses.each do |dose|%>
          <p><%= dose.description %> of <%= dose.ingredient.name%> -
          <%=link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
            <i class="far fa-trash-alt" style="color: #ea5611"></i> </p>
          <% end %>
        <% end %>
      </br>
      <div class="right-bottom">
        <%= link_to 'Add ingredient', new_cocktail_dose_path(@cocktail), class: "btn" %>
      </br>
        <%= link_to 'Homepage', cocktails_path, class: "btn-small" %>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container" style="background-color: #fdce92; width: 900px; height: 100vh; padding: 30px">
  <h1 style="text-align: center">Add a new Dose</h1>
  <div class="second-container">
    <img src= "https://images.unsplash.com/photo-1610218587762-20e80d2d548e?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=624&q=80", alt="cocktail image" style="height: 450px; width: 400px; object-fit: cover; margin-left: 20px;">
    <div class="rightside">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        </br>
        <%= f.button :submit, class: "btn" %>
      <% end %>
      </br>
      <%= link_to 'Homepage', cocktails_path, class: "btn-small" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="preconnect" href="https://fonts.gstatic.com">
  </head>

  <body>
    <%= yield %>
  </body>
  <div class="footer">
    <div class="footer-links">
        <a href="#"><i class="fab fa-github"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</html>